class MenuRendererConfig:
    width = 128
    height = 64
    ssd1306_i2c_address = 0x3c
#    font_path = 'resources/SourceCodePro-Bold.ttf'
    font_path = 'resources/DejaVuSansMono-Bold.ttf'
    font_size = 12
    row_selection_pixel_extension = 2
    scroll_behavior = "page"  # "extend" or "page"
#    scroll_behavior = "extend"  # "extend" or "page"
#    transition = "PushTransition"
    transition = "None"
    transition_attributes_left = {"direction": "push_left"}
    transition_attributes_right = {"direction": "push_right"}
    transition_speed = 20
    scroll_line = True
    scroll_delay = 3
    scroll_line_end_delay = 2
    screensaver_delay = 60
